[manifest]
dump_lua = true
priority = 0
version = "1.3.0"

[[patches]]
[patches.pattern]
match_indent = false
pattern = "if highlighted and self.config.center_key == 'm_prism_double' and self.area == G.hand then"
payload = '''
    if DTM.config.disable_action_buttons and highlighted and self.ability.set == 'Enhanced' and self.ability.name == 'm_prism_double' then
    elseif highlighted and self.config.center_key == 'm_prism_double' and self.area == G.hand then
'''
position = "at"
target = '=[SMODS Prism "objects/enhancements.lua"]'
times = 1
