[manifest]
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
match_indent = false
pattern = '''
elseif self.config.type == 'play' or self.config.type == 'shop' or self.config.type == 'consumeable' then 
    card.states.drag.can = false
'''
payload = '''
if (self.config.type == 'shop') or (self.config.type == 'consumeable') then 
    card.states.drag.can = true
else
    card.states.drag.can = false
end
'''
position = "after"
target = "cardarea.lua"
times = 1
