[manifest]
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.collision_list
'''
position = "before"
payload = '''
--Touch controller
self.touch_control = {s_tap = {target = nil,handled = true}, l_press = {target = nil, handled = true}}
'''
match_indent = false
times = 1

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
--The object being dragged
if self.dragging.target then
    self.dragging.target:drag()
end
'''
position = "before"
payload = '''
--The object being dragged
if not self.dragging.handled then
    print(self.cursor_down.time)
    create_drag_target_from_card(self.dragging.target)
    self.dragging.handled = true
end
'''
match_indent = false
times = 1

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.HID.touch = HID_type == 'touch'
'''
position = "at"
payload = '''
self.HID.touch = HID_type == 'touch' or HID_type == 'mouse'
'''
match_indent = false
times = 1


