[manifest]
version = "1.0.0"

[[patches]]
[patches.copy]
target = "functions/misc_functions.lua"
position = "append"
sources = [
  "overrides/misc_functions.lua"
]

[[patches]]
[patches.copy]
target = "functions/button_callbacks.lua"
position = "append"
sources = [
  "overrides/button_callbacks.lua"
]

[[patches]]
[patches.copy]
target = "functions/UI_definitions.lua"
position = "append"
sources = [
  "overrides/UI_definitions.lua"
]